### ISSUE TITLE
Is this library stable?

### ISSUE THREAD

**Issue by kagile** [commonsguy/cwac-saferoom#11]
Can I use it in production?

**Comment by commonsguy** [comment]
This is an issue tracker, not a support board. The documentation contains [a list of support options](https://github.com/commonsguy/cwac-saferoom#questions). Please use them.

> Is this library stable?

There is not much to the library, and most of the code is from Google, with slight modifications to replace the framework `SQLiteDatabase` with SQLCipher's version. However, [there is no conformance test suite](https://issuetracker.google.com/issues/70669189), so there may need to be some changes.

Also, I have had some discussions with Zetetic (makers of SQLCipher) regarding the long-term direction for SQLCipher and the support database API. It is entirely possible that this project will be discontinued and replaced by something else in the future.

> Can I use it in production?

You are welcome to do whatever you want within the confines of the license. If you feel that your test suite for your own code is pretty strong, using this library is not much riskier than is using plain Room, and your tests should show any problems that get introduced by its use.
