### ISSUE TITLE
Slow response time

### ISSUE THREAD

**Issue by monowar1993** [commonsguy/cwac-saferoom#12]
Fetching data from database is taking bit of a time. As it is lot faster if I do not use saferoom. Is it normal behavior?? Or I need to add some lines of code to make it more optimize? I am currently using the basic setup using SafeHelperFactory.

**Comment by commonsguy** [comment]
This is an issue tracker. It is not a support board. Please read [the project documentation](https://github.com/commonsguy/cwac-saferoom) to learn how to [get support](https://github.com/commonsguy/cwac-saferoom#questions). If you truly feel that there is an issue with this library &mdash; as opposed to an issue with SQLCipher for Android &mdash; please [follow the instructions for filing bug reports](https://github.com/commonsguy/cwac-saferoom/blob/master/CONTRIBUTING.md#contributing-bug-reports). In your case, the demo app would need to show how normal SQLCipher for Android access is noticeably faster than it is by routing it through CWAC-SafeRoom.

In general, an encrypted database will be slower than a non-encrypted database, as encryption is not free. The more data you access, the worse the problem will feel. Optimizing your database schema can help. For example, a database without indexes will perform poorly with SQLite and will perform worse with SQLCipher for Android, as queries have to read in the entire table (i.e., perform a "table scan") to identify the results for the query.

**Comment by monowar1993** [comment]
For encrypted database it takes 4-5 seconds to fetch the data from tables. Also I am using a joined table query. As I cannot provide you a demo app right now. But I'll try using saferoom with indexed tables. I created a issue cause I felt like its data fetching time higher and if a way can fix this issue would be great.
