### ISSUE TITLE
How to remove password/decrypt?

### ISSUE THREAD

**Issue by Blogshot** [commonsguy/cwac-saferoom#14]
I want to enable the user to decrypt his database (remove a password and allow "public" access.

I wonder if providing an empty char[] to rekey() works? Sadly I have no resources to test this myself.

I was wondering about something like:
`SafeHelperFactory.rekey(INSTANCE.getOpenHelper().getWritableDatabase(), new char[]{});`

**Comment by commonsguy** [comment]
This is an issue tracker, not a support board. Support options are shown on [the project `README`](https://github.com/commonsguy/cwac-saferoom#questions).

> Sadly I have no resources to test this myself.

That statement makes no sense. If you do not have an Android device or emulator... how can you be developing an Android app?

> I wonder if providing an empty char[] to rekey() works?

Something along that line should work, AFAIK, but I have not tried it. Track issue #15 for a feature to add this to the API.
