### ISSUE TITLE
Crash on RoomDatabase.init

### ISSUE THREAD

**Issue by sercant** [commonsguy/cwac-saferoom#18]
Using with Room android as mentioned on the README.md crashes with the following stack trace.

Stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-4
                  Process: aware.com.kotlinandroid, PID: 5900
                  java.lang.UnsupportedOperationException: I kinna do it, cap'n!
                      at com.commonsware.cwac.saferoom.Helper.setWriteAheadLoggingEnabled(Helper.java:108)
                      at android.arch.persistence.room.RoomDatabase.init(RoomDatabase.java:113)
                      at android.arch.persistence.room.RoomDatabase$Builder.build(RoomDatabase.java:612)
                      ...
```

Code:
```kotlin
val builder = Room.databaseBuilder(context.applicationContext,
                          AccelerometerRoomDatabase::class.java, "mydatabase.db")
if (encryptionKey != null)
    builder.openHelperFactory(SafeHelperFactory(encryptionKey.toCharArray()))

INSTANCE = builder.build()
```

**Comment by commonsguy** [comment]
My guess is that you are running into [this already reported problem](https://github.com/commonsguy/cwac-saferoom/issues/17). What version of Room are you using?

**Comment by sercant** [comment]
@commonsguy Looks same! Thanks.

PS. Please don't close the issue so people can search/read through the issues and find that it's an existing problem that has not been fixed yet.

**Comment by sercant** [comment]
@commonsguy I have tried setting `JournalMode.TRUNCATE` but since you throw exception no matter what the value of the `boolean enabled`, it doesn't change anything.

```java
  /**
   * {@inheritDoc}
   *
   * NOTE: Not presently supported, will throw an UnsupportedOperationException
   */
  @Override
  @RequiresApi(api = Build.VERSION_CODES.JELLY_BEAN)
  public void setWriteAheadLoggingEnabled(boolean enabled) {
    // TODO not supported in SQLCipher for Android
    throw new UnsupportedOperationException("I kinna do it, cap'n!");
//    delegate.setWriteAheadLoggingEnabled(enabled);
  }
```

**Comment by commonsguy** [comment]
Correct. My preference would be to call through to a native method, as `FrameworkSQLiteDatabase` does, but that is not available with SQLCipher for Android at present (hence, the commented-out call).

I will need to try just using the `PRAGMA` and hope for the best.

**Comment by commonsguy** [comment]
WAL support added in 0.4.1.
