### ISSUE TITLE
incompatible types: SafeHelperFactory cannot be converted to Factory

### ISSUE THREAD

**Issue by r0boto** [commonsguy/cwac-saferoom#32]
Hi, 

I faced with the following problem with using:
`implementation "com.commonsware.cwac:saferoom.x:0.5.0"`

`SafeHelperFactory factory = new SafeHelperFactory(passphrase);`
cannot be applied to 
```
Room.databaseBuilder(context.getApplicationContext(), AppDatabase.class, Constants.Global.DATABASE_NAME)
.openHelperFactory(factory)
```

which accepts Factory objects only. But which Factory class is right? Or use case with using cwac:saferoom.x:0.5.0 is different?

Environment:
**Target:** 28
**Gradle:** classpath 'com.android.tools.build:gradle:3.4.0-alpha02'
**ROOM**
    implementation 'android.arch.persistence.room:runtime:1.1.1'
    annotationProcessor 'android.arch.persistence.room:compiler:1.1.1'
**Android Studio:** 3.2.1

**Comment by commonsguy** [comment]
You are using `android.arch.persistence.room:runtime:1.1.1`. That means you should be using [the Android Support library version of SafeRoom](https://github.com/commonsguy/cwac-saferoom#android-support-library), `com.commonsware.cwac:saferoom`. Do not move to `com.commonsware.cwac:saferoom.x` until you move to `androidx.room`.
