### ISSUE TITLE
BindingsRecorder is bug-1?

### ISSUE THREAD

**Issue by sethleech** [commonsguy/cwac-saferoom#4]
Hi,
I think "BindingsRecorder" class has a bug in function "String[] getBindings()"

`  String[] getBindings() {
    final String[] result=new String[bindings.size()];

    for (int i=0;i<bindings.size();i++) {
      Object binding=bindings.get(i);

      if (binding!=null) {
        result[i]=bindings.get(i).toString();
      }
      else {
        result[i]=""; // SQLCipher does not like null binding values
      }
    }

    return(result);
  }
`
ref : android.arch.persistence.room.RoomSQLiteQuery
1) private constructor comment 
    `because, 1 based indices... we don't want to offsets everything with 1 all the time.`
2) ref method bindTo
   `for (int index = 1; index <= mArgCount; index++)`

so modified code is : bindings.get(i+1)
refer below
`  String[] getBindings() {
    final String[] result=new String[bindings.size()];

    for (int i=0;i<bindings.size();i++) {
      Object binding=bindings.get(i+1);

      if (binding!=null) {
        result[i]=bindings.get(i+1).toString();
      }
      else {
        result[i]=""; // SQLCipher does not like null binding values
      }
    }

    return(result);
  }
`

**Comment by commonsguy** [comment]
> I think "BindingsRecorder" class has a bug in function "String[] getBindings()"

Do you have a test case that demonstrates the bug?

**Comment by sethleech** [comment]
Some do not think as bug. It works right and is not crashed.
But code is not correct

When bound index 1 = 15 and index 2 = 20,  Sparse array variant - bindings is set [1, 15] [2, 20]
returned String[0] = "", returned String[1] = "15"

**Comment by commonsguy** [comment]
Closing this issue as not reproducible. If you come up with a test case that demonstrates the problem, attach it, and I can reopen the issue.
