### ISSUE TITLE
file is not a database: , while compiling: select count(*) from sqlite_master

### ISSUE THREAD

**Issue by mfaisal881996** [commonsguy/cwac-saferoom#43]
Sir i'm trying to enrcypt and decrypt the database with a key from c++ file which is a getlogin method 
but when ever i enrcypt or decrypt database it shows this error but still the database is enrcypted and decrypted

package Database;

import android.content.Context;
import android.os.Build;
import android.util.Log;

import com.commonsware.cwac.saferoom.SQLCipherUtils;
import java.io.File;
import java.io.IOException;

import Common.Common;

public class EncryptionDecryption {

    static {
        System.loadLibrary("native-lib");
    }

    public native String invokeNativeFunction();
    private Context context;

    public EncryptionDecryption(Context context) {
        this.context = context;
    }

    private String keysOfEncryption(){

        String keyOne = Build.USER + Build.BOARD;
        keyOne += invokeNativeFunction();
        return keyOne;
    }

    public void encryptDatabase(){
        String Startstate = String.valueOf(SQLCipherUtils.getDatabaseState(context.getApplicationContext(),"user-database"));
        if(Startstate.equalsIgnoreCase("UNENCRYPTED")) {
            try {
                SQLCipherUtils.encrypt(context.getApplicationContext(), "user-database", keysOfEncryption().toCharArray());
                Common.DATABASE_STATE = "ENCRYPTED";
                Log.d("Database", "encryptDatabase: "+Common.DATABASE_STATE);
                Log.d("Database", "encryptDatabase key : "+keysOfEncryption());
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public void decryptDatabase(){
        File databasepath = context.getDatabasePath("user-database");
        String state = String.valueOf(SQLCipherUtils.getDatabaseState(context.getApplicationContext(),"user-database"));
        if(state.equalsIgnoreCase("encrypted")) {
            try {
                SQLCipherUtils.decrypt(context.getApplicationContext(), databasepath, keysOfEncryption().toCharArray());
                Common.DATABASE_STATE = "UNENCRYPTED";
                Log.d("Database", "decryptDatabase: "+Common.DATABASE_STATE);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
}

**Comment by commonsguy** [comment]
I cannot really help you, as I do not have:

- the Android OS version on which you are experiencing the problem
- the *complete* code necessary to reproduce the problem (in your case, I do not have a full set of code, as I lack `native-lib`)
- the steps necessary, using that code and that version of Android, to reproduce the problem

BTW, using hardcoded keys (my interpretation of "a key from c++ file") is pointless. Either get the key from the user or do not bother encrypting the database.

**Comment by Sinarahimi** [comment]
Hi 
I have the same problem. I think its about how we use it.
`
SafeHelperFactory factory = new SafeHelperFactory(passphrase);
`
`
        appDatabase = Room.databaseBuilder(context, AppDatabase.class, DATABASE_DB)
                .openHelperFactory(factory)
                .allowMainThreadQueries()
                .build();
`
When I added the `openHelperFactory(factory) ` to the builder and trying to read from db , it gets this error.

> file is not a database: , while compiling: select count(*) from sqlite_master

At first I thought that the db was encrypted but it wasn't .

**Comment by commonsguy** [comment]
@Sinarahimi If you have existing Room code, and you have an existing Room database, you cannot just add in `SafeRoom`. You would need to [encrypt the database](https://github.com/commonsguy/cwac-saferoom#encrypting-existing-databases), then add in SafeRoom.

**Comment by Sinarahimi** [comment]
I downgrade my Room from 1.1.1 to 1.1.0 and I changed my code to this 

`

     SafeHelperFactory factory = new SafeHelperFactory(passphrase);
        File file = new File(String.valueOf(context.getDatabasePath(dbName)));

        appDatabase = Room.databaseBuilder(context, AppDatabase.class, DATABASE_DB)
                .openHelperFactory(factory)
                .allowMainThreadQueries()
                .build();
        SQLCipherUtils.State  state = SQLCipherUtils.getDatabaseState(file);
        if (state.equals(UNENCRYPTED)) {
            try {
                SQLCipherUtils.encrypt(context,file,passphrase);

            } catch (IOException e) {
                e.printStackTrace();
            }
        }
`
I still get the same error on this line :

`SQLCipherUtils.State  state = SQLCipherUtils.getDatabaseState(file);`

But this time it didn't crash . The question here is that I pulled out the db files and they are all encrypted, And I didn't decrypted them but when I do query on it, It works like its not encrypted at all.

**Comment by commonsguy** [comment]
I would encrypt the database before creating the `RoomDatabase`.

Please either [use the available support options](https://github.com/commonsguy/cwac-saferoom#questions) or [provide a reproducible test project](https://github.com/commonsguy/cwac-saferoom/blob/master/CONTRIBUTING.md#contributing-bug-reports).

**Comment by hannesa2** [comment]
@Sinarahimi I've seen a similar issue as we switched from `0.5.0` to `0.5.1`, but the further switch to `1.0.0` solved it. -no clue why-
The **code** changes from `0.5.0` to `0.5.1` looks not suspect, but as the **delivered lib is a black box**, because it hasn't a deterministic/public build and the maintainer don't want a deterministic build https://github.com/commonsguy/cwac-saferoom/pull/40 -sad-

Who uses this lib (@commonsguy thank you for sharing/creating it !) is interested in security and at the same time, you should ask what or whom to trust.

That's why I made a [fork](https://github.com/hannesa2/cwac-saferoom) with a **deterministic** and **public** build https://github.com/hannesa2/cwac-saferoom/pull/2 Nothing is build local and commit/build it automatic written into `BuildConfig.java` so you can verify what you have/use

**Comment by manishakamble** [comment]
> I downgrade my Room from 1.1.1 to 1.1.0 and The code was changed to this
> 
> `
> 
> ```
>  SafeHelperFactory factory = new SafeHelperFactory(passphrase);
>     File file = new File(String.valueOf(context.getDatabasePath(dbName)));
> 
>     appDatabase = Room.databaseBuilder(context, AppDatabase.class, DATABASE_DB)
>             .openHelperFactory(factory)
>             .allowMainThreadQueries()
>             .build();
>     SQLCipherUtils.State  state = SQLCipherUtils.getDatabaseState(file);
>     if (state.equals(UNENCRYPTED)) {
>         try {
>             SQLCipherUtils.encrypt(context,file,passphrase);
> 
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
>     }
> ```
> 
> `
> I still get the same error on this line :
> 
> `SQLCipherUtils.State state = SQLCipherUtils.getDatabaseState(file);`
> 
> But this time it didn't crash . The question here is that I pulled out the db files and they are all encrypted, And I didn't decrypted them but when I do query on it, It works like its not encrypted at all.

@Sinarahimi  thank you so much . it helps me.
