### ISSUE TITLE
Open encrypted database on developer machine

### ISSUE THREAD

**Issue by hannesa2** [commonsguy/cwac-saferoom#44]
I pulled encrypted database from Android device and tried to open database on developer machine most recent with "DB Browser for SQLite". I used the password and page size 1024 (right ?)

I was able to open database, but there are no tables included (but I see it on Android app)

My question:
How to open such a encrypted database ?
What's the best approach, maybe with command line ?

**Comment by commonsguy** [comment]
> How to open such a encrypted database ?
> What's the best approach, maybe with command line ?

I just use the Android app that I wrote. I have not had a need to examine a SQLCipher for Android database outside of there. And, regardless, this has nothing to do with SafeRoom &mdash; your question is about SQLCipher.

Please, in the future, follow [the instructions in the project `README`](https://github.com/commonsguy/cwac-saferoom#questions) for getting help with this library, and use Zetetic resources for getting help with SQLCipher.

**Comment by hannesa2** [comment]
But you can share your knowledge !

**Comment by commonsguy** [comment]
Yes, but that's what [the instructions in the project `README` for getting help](https://github.com/commonsguy/cwac-saferoom#questions) are for. I don't mind answering questions (where I can), but it would be nice if they were asked in a better place than an issue tracker.
