### ISSUE TITLE
DatabaseObjectNotClosedException and SQLiteException

### ISSUE THREAD

**Issue by hannesa2** [commonsguy/cwac-saferoom#47]
This is related to https://github.com/sqlcipher/android-database-sqlcipher/issues/427#issuecomment-471726172 (and https://github.com/sqlcipher/android-database-sqlcipher/issues/429)

# A

> There is no problem, strictly speaking

I've 6 apps which are crashing and I can't reproduce it. I only see it in Crashlytics. **There is a problem**, the question is where ?
Btw SQLCipher is spamming Crashlytics additionally, but this is more SQLCipher related

# B

> Room does not close the database automatically. ... as we do not necessarily know a good time to close a database.

When I use native Room, I don't see this crashes.

Me too, I don't know a good time to close database, _if this is really the main reason_. 
Most of the crashes come from the background, from JobServices or similar
But how to get rid of it ?

**Comment by commonsguy** [comment]
> There is a problem, the question is where ?

I have no idea.

> But how to get rid of it ?

I have no idea.

In the future, please [follow the instructions for getting support](https://github.com/commonsguy/cwac-saferoom#questions) and please [follow the instructions for filing issues](https://github.com/commonsguy/cwac-saferoom/blob/master/CONTRIBUTING.md#contributing-bug-reports).
