### ISSUE TITLE
Package Size too large

### ISSUE THREAD

**Issue by frankyenshaw** [commonsguy/cwac-saferoom#48]
Hello,

Including com.commonsware.cwac:saferoom.x:1.0.1 increases the size of my android app from 15MB.  I have very strict size requirements for my application, is there any way to take advantage of the room DB encryption without so much overhead?

Thanks

**Comment by commonsguy** [comment]
This has nothing to do with SafeRoom directly. Your size is coming from SQLCipher for Android, which uses native libraries and bundles them for every CPU architecture. As I discussed [on the SQLCipher support board](https://discuss.zetetic.net/t/sqlcipher-for-android-room-and-api-level-16/2161/35), you can look into using product flavors or APK splits to have separate APKs per CPU architecture.
