### ISSUE TITLE
ERROR: Failed to resolve: com.commonsware.cwac:saferoom:1.0.2

### ISSUE THREAD

**Issue by altagir** [commonsguy/cwac-saferoom#49]
the URL https://s3.amazonaws.com/repo.commonsware.com does not seem to contain the saferoom package

**Comment by commonsguy** [comment]
Um, yes it does. See for example https://s3.amazonaws.com/repo.commonsware.com/com/commonsware/cwac/saferoom.x/1.0.2/index.html and the files that it links to.

What are your specific symptoms?

**Comment by altagir** [comment]
I have :
ERROR: Failed to resolve: com.commonsware.cwac:saferoom:1.0.2

when adding 

> maven { url "https://s3.amazonaws.com/repo.commonsware.com" }


and

> implementation "com.commonsware.cwac:saferoom:1.0.2"

as specified in this repo

**Comment by altagir** [comment]
the URL https://s3.amazonaws.com/repo.commonsware.com does not list saferoom in their XML

**Comment by commonsguy** [comment]
> I have : ERROR: Failed to resolve: com.commonsware.cwac:saferoom:1.0.2

Can you provide the entire build output? It should show the places where it is trying to load the artifact. FWIW, I put those lines into a test project, and they worked just fine.

> the URL https://s3.amazonaws.com/repo.commonsware.com does not list saferoom in their XML

It doesn't have to.

**Comment by altagir** [comment]
> Could not find com.commonsware.cwac:saferoom:1.0.2.
> Searched in the following locations:
>   - file:/Users/ssenechal/Library/Android/sdk/extras/m2repository/com/commonsware/cwac/saferoom/1.0.2/saferoom-1.0.2.pom
>   - file:/Users/ssenechal/Library/Android/sdk/extras/m2repository/com/commonsware/cwac/saferoom/1.0.2/saferoom-1.0.2.jar
>   - file:/Users/ssenechal/Library/Android/sdk/extras/google/m2repository/com/commonsware/cwac/saferoom/1.0.2/saferoom-1.0.2.pom
>   - file:/Users/ssenechal/Library/Android/sdk/extras/google/m2repository/com/commonsware/cwac/saferoom/1.0.2/saferoom-1.0.2.jar
>   - file:/Users/ssenechal/Library/Android/sdk/extras/android/m2repository/com/commonsware/cwac/saferoom/1.0.2/saferoom-1.0.2.pom
>   - file:/Users/ssenechal/Library/Android/sdk/extras/android/m2repository/com/commonsware/cwac/saferoom/1.0.2/saferoom-1.0.2.jar
>   - https://dl.google.com/dl/android/maven2/com/commonsware/cwac/saferoom/1.0.2/saferoom-1.0.2.pom
>   - https://dl.google.com/dl/android/maven2/com/commonsware/cwac/saferoom/1.0.2/saferoom-1.0.2.jar
>   - https://jcenter.bintray.com/com/commonsware/cwac/saferoom/1.0.2/saferoom-1.0.2.pom
>   - https://jcenter.bintray.com/com/commonsware/cwac/saferoom/1.0.2/saferoom-1.0.2.jar
>   - file:/Users/ssenechal/.m2/repository/com/commonsware/cwac/saferoom/1.0.2/saferoom-1.0.2.pom
>   - file:/Users/ssenechal/.m2/repository/com/commonsware/cwac/saferoom/1.0.2/saferoom-1.0.2.jar
> Required by:
>     project :app

**Comment by commonsguy** [comment]
You did not add `maven { url "https://s3.amazonaws.com/repo.commonsware.com" }` to your list of repositories. It is not among those that Gradle searched for the artifact.

If you have a typical modern Android Studio project, add that `maven` line to the top-level `build.gradle` file, as [this repo's project does](https://github.com/commonsguy/cwac-saferoom/blob/v1.0.2/build.gradle#L15-L20).

**Comment by altagir** [comment]
Hi, I just realized I did include that line inside a buildscript { repositories {} }, similar to another lib I used (Fabric)
Placing the repository line outside the buildscript fixed the issue
sorry i am pretty new to gradle, thanks for your help ! Appreciated
