### ISSUE TITLE
Support byte array passwords

### ISSUE THREAD

**Issue by iskugor** [commonsguy/cwac-saferoom#51]
Hello.

Since Sqlcipher supports password as byte array: https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SQLiteDatabase.java#L1235

can we get saferoom also to support it?

Thanks!

**Comment by commonsguy** [comment]
I'll look into it &mdash; thanks for the suggestion!

**Comment by chrisharris77** [comment]
I would also very much like to be able to use a byte array key instead of a passphrase.

**Comment by commonsguy** [comment]
Are you using `saferoom.x` (AndroidX) or `saferoom` (Android Support Library)? I would like to post a `SNAPSHOT` artifact for you to try out.

**Comment by iskugor** [comment]
I'm using AndroidX. Thanks.

**Comment by commonsguy** [comment]
@iskugor OK, try `implementation "com.commonsware.cwac:saferoom.x:1.0.3-SNAPSHOT". [`SafeHelperFactory` now has `byte[]` constructors that mirror the `char[]` ones](https://github.com/commonsguy/cwac-saferoom/commit/2c8444cb473e454292ff5a292e2d0259b0348737).

Let me know if you run into any problems!

**Comment by iskugor** [comment]
@commonsguy sorry for late reply, I tried 1.0.3 snapshot and for now it looks like it works great. Thanks!

**Comment by commonsguy** [comment]
OK, this feature is in `1.0.3`. Let me know if you run into any problems with it!
