### ISSUE TITLE
Support byte array passwords - Part 2

### ISSUE THREAD

**Issue by opt05** [commonsguy/cwac-saferoom#52]
You recently added byte[] support in 1.0.3 via #51 but can this also be added for the other functions that currently take a char[] as well? Such as the `SQLCipherUtils.decrypt()` & `SQLCipherUtils.encrypt()` functions specifically? Thank you!

**Comment by commonsguy** [comment]
OK, I'll look into it -- thanks for the suggestion!

**Comment by commonsguy** [comment]
I can offer `byte[]` editions of those, but not of `rekey()` (SQLCipher for Android doesn't have a `byte[]` variant of the `changePassword()` method that I use in `rekey()`).

Are you using the AndroidX or Android Support version of SafeRoom? As with 1.0.3, I'd like to publish a `SNAPSHOT` release of a 1.0.4 for you to try.

**Comment by opt05** [comment]
I think that is fine as I don't personally use the rekey() method but I am on the AndroidX version and will be glad to test the snapshot, thanks!

**Comment by commonsguy** [comment]
OK, try `1.0.4-SNAPSHOT`. It has `byte[]`variants of `encrypt()` and `decrypt()`: https://github.com/commonsguy/cwac-saferoom/commit/fd6d8050c7f3a45c2dc18f66a31943d07a22045b

**Comment by opt05** [comment]
Tested both encrypt() and decrypt() and it is working as intended like the char[] version, thanks!

**Comment by commonsguy** [comment]
OK, `1.0.4` final is out with this change -- thanks again!
