### ISSUE TITLE
Disable WAL when encrypt

### ISSUE THREAD

**Issue by NiaNingXue** [commonsguy/cwac-saferoom#59]
Hi, I set JournalMode to TRUNCATE in Room builder, but when encrypted ,the db file is still WAL.
Is there a way to config the encrypted db truncated?

**Comment by commonsguy** [comment]
> I set JournalMode to TRUNCATE in Room builder, but when encrypted ,the db file is still WAL.

Without a sample project that can reproduce your behavior, I have no way of advising you on your code.

**Comment by NiaNingXue** [comment]
Thanks for your quick. In fact, I want to back up the encrypted db file, but even I set JournalMode to TRUNCATE, it still has three files.
     `                    SafeHelperFactory factory= new SafeHelperFactory(context.getPackageName().toCharArray());
                    INSTANCE = Room.databaseBuilder(context.getApplicationContext(),
                            VaultDatabase.class, DB_NAME)
                            .openHelperFactory(factory)
                            .setJournalMode(JournalMode.TRUNCATE)
                            .build();`
This is the init code.
![QQ图片20190701193820](https://user-images.githubusercontent.com/5886258/60433603-c1f69900-9bf4-11e9-9ddd-44134059e46a.png)
Three db files indicate that it is still WAL mode

**Comment by commonsguy** [comment]
Try calling `isWriteAheadLoggingEnabled()` on your `SQLiteDatabase` that you get from your code shown above. Does it return true or false?

**Comment by NiaNingXue** [comment]
it returns false. That indicates the original room db is truncate mode, but the sqlcipher is WAL mode, it there a way to set sqlcipher in truncate mode?

**Comment by commonsguy** [comment]
> That indicates the original room db is truncate mode

I do not know what you mean by "the original room db".

> it there a way to set sqlcipher in truncate mode?

Try calling `disableWriteAheadLogging()` on your `SQLiteDatabase`. See [`WALTests`](https://github.com/commonsguy/cwac-saferoom/blob/v1.1.0/saferoom/src/androidTest/java/com/commonsware/cwac/saferoom/test/WALTest.java) for an example.

**Comment by NiaNingXue** [comment]
My English is poor, thanks for your help.

**Comment by NiaNingXue** [comment]
@commonsguy  Hi, I have finished the backup
```
 SQLiteDatabase.loadLibs(context);
        File originalFile = context.getDatabasePath(VaultDatabase.DB_NAME);
        File backupFile = new File(FileUtils.createParentDir(), "backup.db");
        try {
            if (backupFile.exists()) {
                backupFile.delete();
            }
            backupFile.createNewFile();
        } catch (IOException e) {
            e.printStackTrace();
        }
        SQLiteDatabase db =
                SQLiteDatabase.openDatabase(originalFile.getAbsolutePath(),
                        context.getPackageName().toCharArray(), null, SQLiteDatabase.OPEN_READWRITE, null, null);

        final SQLiteStatement st = db.compileStatement("ATTACH DATABASE ? AS plaintext KEY ''");

        st.bindString(1, backupFile.getAbsolutePath());
        st.execute();

        db.rawExecSQL("SELECT sqlcipher_export('plaintext')");
        db.rawExecSQL("DETACH DATABASE plaintext");

        int version = db.getVersion();

        db.close();

        db = SQLiteDatabase.openDatabase(backupFile.getAbsolutePath(), "", null, SQLiteDatabase.OPEN_READWRITE);
        db.setVersion(version);
        db.close();
```
It back up the encrypted db file as plain. But I do not know how to restore, I try to restore like below
```
 SQLiteDatabase.loadLibs(context);
        File backupFile = new File(FileUtils.createParentDir(), "backup.db");
        if (backupFile.exists()) {
            try {
                File newFile = File.createTempFile("sqlcipherutils", "tmp", context.getCacheDir());
                SQLiteDatabase db =
                        SQLiteDatabase.openDatabase(backupFile.getAbsolutePath(),
                                "", null, SQLiteDatabase.OPEN_READWRITE);
                int version = db.getVersion();

                db.close();

                db = SQLiteDatabase.openDatabase(newFile.getAbsolutePath(), context.getPackageName().toCharArray(),
                        null, SQLiteDatabase.OPEN_READWRITE, null, null);
                db.enableWriteAheadLogging();
                final SQLiteStatement st = db.compileStatement("ATTACH DATABASE ? AS plaintext KEY ''");

                st.bindString(1, backupFile.getAbsolutePath());
                st.execute();

                db.rawExecSQL("SELECT sqlcipher_export('main', 'plaintext')");
                db.rawExecSQL("DETACH DATABASE plaintext");
                db.setVersion(version);
                db.close();
                File dbFile = context.getDatabasePath(VaultDatabase.DB_NAME);
                dbFile.delete();
                newFile.renameTo(dbFile);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
```
It seems just copy the file or the data, when in runtime , I can not get the data from room. Can you give me some suggestion. Thank you.

**Comment by commonsguy** [comment]
This code is not using SafeRoom, and this is an issue tracker for SafeRoom. This is not a support board for SQLCipher for Android in general. Also, I do not know what "I can not get the data from room" means in terms of code, symptoms, etc. 

Note, though, that `db.enableWriteAheadLogging()` means that you have three files to move, not just one. I would disable WAL for the restore operation, for the same reasons that you cited earlier in this issue. Using WAL for normal database I/O is fine, but for this sort of import/export work, I would disable WAL.

**Comment by NiaNingXue** [comment]
Thanks , I have disabled WAL and copy the db file by myself.  it works.
