### ISSUE TITLE
Is it possible to use this with an existing Room database?

### ISSUE THREAD

**Issue by pcqpcq** [commonsguy/cwac-saferoom#6]
I created database with Room, but I didn't use SQLCipher at that time.
So, is it possible to do this with saferoom now? And, how?

**Comment by commonsguy** [comment]
My guess is that you would have to treat this similarly to how you convert an existing SQLite database to SQLCipher for Android without Room. Dealing with the Room metadata will be tricky. I have not tried any of this, but I'll look into it at some point.

**Comment by pcqpcq** [comment]
Thanks! I'll make a pr if I found anything useful. 👍

**Comment by commonsguy** [comment]
FYI, I'll be pushing an update tomorrow or this weekend that offers a `SQLCipherUtils` class that contains an `encrypt()` method to encrypt a regular SQLite database. The docs will show how to use it with Room and `SafeHelperFactory`.

**Comment by commonsguy** [comment]
Addressed in v0.2.0 -- thanks!
