### ISSUE TITLE
Can't create encrypted room database with empty char[]

### ISSUE THREAD

**Issue by babogoos** [commonsguy/cwac-saferoom#63]
In my app, I need to build an  non-encrypted database when i build with debug Flavors;

I have two database in my app, one of them using SQLiteOpenHelper, so I use the zetetic solution (version: 4.2.0), 
For the non-encrypted db I'm using :-
`mDatabaseHelper.getWritableDatabase("");`
and it works!

The other db is Room Database, I use  cwac-saferoom,
For the room non-encrypted db I'm using :-
`private static SafeHelperFactory factory = new SafeHelperFactory(new char[]{});`

there is no error when the database create,
but when I trying to use the Dao in my RoomDatabase to query some data.
it cause 
> java.lang.NullPointerException: Attempt to get length of null array

I have no idea, what's wrong?
Is there any suggestion that how to create a non-encrypted Room database?

Since zetetic haven't support Room, cwac-saferoom is the best solution for encrypt room database, Please help, thanks!

**Comment by commonsguy** [comment]
The equivalent of `""` in a `char[]` is `"".toCharArray()`, so try that.

**Comment by babogoos** [comment]
`"".toCharArray()`
Still crash when use the Dao in my RoomDatabase to query some data.
cause: 
> java.lang.NullPointerException: Attempt to get length of null array

However, I figure out a way to bypass this situation.

SafeHelperFactory is a  Room openHelperFactory plugin,
so I am doing this way,
`
RoomDatabase.Builder builder;
if (BuildConfig.FLAVOR != "develop") {
builder.openHelperFactory(new SafeHelperFactory(password.toCharArray()));
}
builder.build();
`
This way will not encrypt Room database when the flavor is "develop", it works.
Hope can help other people who has same problem here.

thanks for reply @commonsguy. 😄

**Comment by commonsguy** [comment]
That was a bug. `"".toCharArray()` works now with `1.1.3`. Thanks for the bug report!
