### ISSUE TITLE
Database corrupted after access with wrong OpenHelperFactory

### ISSUE THREAD

**Issue by zapotec83** [commonsguy/cwac-saferoom#73]
I am doing tests to check whether I use your library on my app or not. I am having the following (maybe normal) behaviour:

- I create the Database using your Helper:

```
                    INSTANCE = androidx.room.Room.databaseBuilder(context.getApplicationContext(),
                            EProDB.class, DBConstants.DATABASE_NAME)
                            .openHelperFactory(factory) // Add Factory to integrate with SaveRoom
                            .fallbackToDestructiveMigration()
                            .build();

```
I insert data in my Database, acess the data and everything goes well.

The problem arrived when I tried to access the Database through "Stetho" (it was to check the Database was really encrypted). Once I did that, I cannot access any more data, it is like if the Database was corrupted or something.

I did another test which is to create the Database again using your SafeHelperFactory factory.
Then, I relaunched the app without using it, and I have the same result, the Database is not accesible anymore even after relaunching the app with your helper.

When I mean that I cannot access my Database, it means that I cannot do a "select" anymore, the return is always null.

I try to retrieve logs, but I don't have any.

Is it a normal behaviour?

In that case, How can I detect that my Database is corrupted due to unauthorised access?

Steps to reproduce: 
1 - Launch app and create DB with the following code: 
```
                    INSTANCE = androidx.room.Room.databaseBuilder(context.getApplicationContext(),
                            EProDB.class, DBConstants.DATABASE_NAME)
                            .openHelperFactory(factory) // Add Factory to integrate with SaveRoom
                            .fallbackToDestructiveMigration()
                            .build();

```

2 - Insert data in DB.
3 - Launch again the app with the following code: 

```
                    INSTANCE = androidx.room.Room.databaseBuilder(context.getApplicationContext(),
                            EProDB.class, DBConstants.DATABASE_NAME)
                            .fallbackToDestructiveMigration()
                            .build();

```

4 - Relaunch the app for the third time with : 
```
                    INSTANCE = androidx.room.Room.databaseBuilder(context.getApplicationContext(),
                            EProDB.class, DBConstants.DATABASE_NAME)
                            .openHelperFactory(factory) // Add Factory to integrate with SaveRoom
                            .fallbackToDestructiveMigration()
                            .build();

```

**Comment by commonsguy** [comment]
> Once I did that, I cannot access any more data, it is like if the Database was corrupted or something.

It is encrypted. That is the point behind SQLCipher for Android. SafeRoom is a bridge between `androidx.sqlite` clients like Room and SQLCipher for Android.

> Then, I relaunched the app without using it, and I have the same result, the Database is not accesible anymore even after relaunching the app with your helper.

Try it again without `fallbackToDestructiveMigration()` in step 3 and see if you have better results.

> Is it a normal behaviour?

You cannot access a SQLCipher for Android database without using SQLCipher for Android and the correct passphrase, if that is what you mean.

> How can I detect that my Database is corrupted due to unauthorised access?

If the database has been tampered with, SQLCipher for Android will refuse to open it. SQLCipher for Android will give you the same error if you try using the wrong passphrase.

**Comment by zapotec83** [comment]
Thanks! I understood, so It is not a bug, what it is actually happening is that If I try to open without SafeHelperFactory, it destroys the encrypted DB (cause of fallbackToDestructiveMigration())  and Room creates a new non-encrypted DB, so that's why I cannot correctly access my data

**Comment by commonsguy** [comment]
> what it is actually happening is that If I try to open without SafeHelperFactory, it destroys the encrypted DB (cause of fallbackToDestructiveMigration()) and Room creates a new non-encrypted DB, so that's why I cannot correctly access my data

That is my theory &mdash; hopefully, you can confirm that with tests (if you have not done so already). Ideally, `fallbackToDestructiveMigration()` would have no effect if Room could not open the database in the first place. I have never used `fallbackToDestructiveMigration()`, so I do not know its precise impact.

In terms of Stetho, you might see if somebody has created a Stetho version that supports SQLCipher for Android.
