### ISSUE TITLE
Include license in pom.xml

### ISSUE THREAD

**Issue by arekolek** [commonsguy/cwac-saferoom#75]
Please consider adding a `<licenses>` in the `pom.xml` when publishing http://maven.apache.org/pom.html#Licenses

This way tools like:

- https://github.com/google/play-services-plugins
- https://github.com/jaredsburrows/gradle-license-plugin/
- https://github.com/hierynomus/license-gradle-plugin
- https://github.com/mikepenz/AboutLibraries

will have a way to determine the license of project dependencies.

**Comment by commonsguy** [comment]
As is noted in [the project `README`](https://github.com/commonsguy/cwac-saferoom), this project is no longer under active development, as it is no longer needed. Just use the latest version of SQLCipher for Android, and it already has `SupportSQLite*` implementations for you.
