### ISSUE TITLE
Deleting database or clear tables

### ISSUE THREAD

**Issue by EhsanMashhadi** [commonsguy/cwac-saferoom#76]
Hi,
I want to delete the encrypted room files or clear its tables. 

The Room has a function which name is ```clearAllTables()```, but I cannot get the database instance without a password. 

Is there any other solution, or should I delete the file in the database folder?

**Comment by commonsguy** [comment]
Please use SQLCipher for Android directly &mdash; version 4.2.0 and higher offers `SupportSQLite*` classes directly, so you no longer need this library.

If you do not have a passphrase, your only option is to delete the database files.

**Comment by EhsanMashhadi** [comment]
What is your suggestion to find related files of the room database? Each database creates three files:
file, file-shm, and file-wal. Is there any solution to get all associated files of a database?

**Comment by commonsguy** [comment]
By default the database is stored in the location identified by `getDatabasePath()`, a method on `Context`.

**Comment by EhsanMashhadi** [comment]
Is it safe to delete all the files in this path? What if any libraries have a database for itself? Ido not want to delete those databases.

**Comment by commonsguy** [comment]
`getDatabasePath()` takes the name of a database file. It will return a `File` that points to a single file, representing your database. If you wish to try modify that `File` to check for and delete `-shm` and `-wal` files, you can do so. None of that will affect any other databases.

**Comment by EhsanMashhadi** [comment]
Thanks!
