### ISSUE TITLE
"file is not a database: , while compiling: select count(*) from sqlite_master; "

### ISSUE THREAD

**Issue by zloykurd** [commonsguy/cwac-saferoom#77]
Hello!, works fine on most devices, but there are those who crash after 2-3 weeks of use. With exception "file is not a database: , while compiling: select count(*) from sqlite_master; " 

how fix this error ?

use example:

      SafeHelperFactory.Options options = SafeHelperFactory.Options
                .builder()
                .setClearPassphrase(false)
                .build();

        val factory = SafeHelperFactory.fromUser(new SpannableStringBuilder("123456789xx"), options);
        return Room.databaseBuilder(application, AppDatabase.class, mDBName)
                .openHelperFactory(factory)
                .addMigrations(
                        MIGRATION_1_2,
                        MIGRATION_2_3,
                )
                .build();

**Comment by commonsguy** [comment]
As is noted on the project home page, this project is no longer under active development. You should no longer be using this library. SQLCipher for Android supports Room directly.

Beyond that, the most common reason for this message is an incorrect passphrase.

**Comment by hannesa2** [comment]
> Beyond that, the most common reason for this message is an incorrect passphrase.

That's not right. There is a systematic error in SQLCipher for Android. ~ 2% of our 10 million user devices run into this error with a **fix** passphrase.

> You should no longer be using this library

But as your wrote 👍
